# Deployment
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: deployment-hellonode 
  # Este label es del Deployment (No tiene que ser el mismo que el de los pods) 
  labels:
    app: hellonode
spec: 
  replicas: 3 
  selector: 
    # Este serian los labels que debe buscar el replicaSet 
    matchLabels: 
      app: hellonode
  template: 
    metadata: 
      # Estos son los labels de los pods 
      labels: 
        app: hellonode
    spec: 
      containers: 
      - name: hellonode
        # Imagen de repositorio
        # image: localhost:5000/nodetest
        image: nodetest
        # Si tenemos la imagen en local tenemos que cambiar la politica de pull
        imagePullPolicy: IfNotPresent

---
# nodeport
apiVersion: v1
kind: Service
metadata:
  name: testdockerfile
  labels:
    app: hellonode
spec:
  type: NodePort
  selector:
    app: hellonode
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
