FROM alpine:latest as builder
WORKDIR /app
COPY package.json .
COPY server.js .
RUN apk add npm &&  npm install

FROM alpine:latest
RUN apk add nodejs
WORKDIR /app 
COPY --from=builder /app . 
CMD ["node", "server.js"]

